server.port=8082
#Enable Actuator
management.endpoints.web.exposure.include=*

# DataSource Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=chairmansdb;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=20
application.theme.color=yellow
